---
Title: "Copper, lead, and zinc tolerance and accumulation in the Australian rattle pods Crotalaria novae-hollandiae, C. medicaginea, and C. mitchellii"
Collection: publications
Category: manuscripts
Link: /publication/2024-10-28-Metal-Accumulation-in-Australian-Rattle-Pods
Excerpt: 'Crotalaria is a genus of ~600 species of legumes predominantly found in (sub)tropical regions of Africa and Australia. Crotalaria novae-hollandiae from Australia is a polymetallic zinc (Zn)-cadmium(Cd)-copper(Cu) hyperaccumulator, but only when growing in metalliferous soils. This study aimed to test metal tolerance in Australian Crotalaria species to establish whether metal tolerance is a trait shared between Crotalaria species not known to occur on metalliferous soils. The hyperaccumulator Crotalaria novae-hollandiae and two non-metallophytes, Crotalaria mitchellii and Crotalaria medicaginea, were exposed to different treatments containing Cu-lead(Pb)-Zn in the form of spiked soils. Foliar samples were analyzed for total elemental concentrations and spectrophotometric analysis was undertaken to assess photosynthetic pigments (chlorophyll a + b and carotenoids) as indicators of stress and polyphenols as an indicator of tolerance. No significant differences in metal accumulation were found in the Crotalaria species, and all exhibited a high level of tolerance toward Zn. However, C. novae-hollandiae exhibited the greatest tolerance toward Zn but had low tolerance toward Cu, while none accumulated foliar Pb. Tolerance to Zn appears to be a trait shared between the Crotalaria species tested. None of the tested Crotalaria species exhibited tolerance toward Cu, and none accumulated Pb.'
Date: 28 Oct 2024
Journal: 'Ecological Research'
URL: 'https://esj-journals.onlinelibrary.wiley.com/doi/epdf/10.1111/1440-1703.12535'
Citation: 'Tang, R. H., Salinitro, M., Nkrumah, P. N., Erskine, P. D., & van der Ent, A. (2024). Copper, lead, and zinc tolerance and accumulation in the Australian rattle pods Crotalaria novae-hollandiae, C. medicaginea, and C. mitchellii. Ecological Research, 39(6), 966–976. https://doi.org/10.1111/1440-1703.12535'
---
The contents above will be part of a list of publications, if the user clicks the link for the publication than the contents of section will be rendered as a full page, allowing you to provide more information about the paper for the reader. When publications are displayed as a single page, the contents of the above "citation" field will automatically be included below this section in a smaller font.
